name: Jekyll site CI

on:
  pull_request:
    paths: 
      - 'client/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      run: cd client && npm install && npm test
