name: testing code

on:
  pull_request:
    paths:
      -'client/**'
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      run: cd client && npm install && npm test
